### ISSUE TITLE
CONSTRUCCION SOBRE EL CONOCIMIENTO INFOGRAFIA

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-2-infografia-irvinjs22620075#1]
![INFOGRAFIA CONSTRUCCION DEL CONOCIMIENTO](https://user-images.githubusercontent.com/112287287/187570488-3cc9b763-2080-406e-a15c-bd1542954336.jpg)

**Comment by 11042002** [comment]
Tu calificación es de: 18.5%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
